######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : noble-gas-reduction, Index = 0, Count = null
# SUBMIT FILE NAME : register_local_2_0.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 PATH=/usr/bin:/bin CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=d3326321-b47e-49e9-8e88-50e0138644d1 PEGASUS_WF_LABEL=noble-gas-reduction PEGASUS_DAG_JOB_ID=register_local_2_0 PEGASUS_SITE=local _PEGASUS_WF_SUBMIT_DIR=/home/vsaiadian/Hotsprings/workflow/work/vsaiadian/pegasus/noble-gas-reduction/run0002 PEGASUS_BIN_DIR=/usr/bin"
arguments = "pegasus-kickstart  -n pegasus::rc-client -N null -R local  -L noble-gas-reduction -T 2026-10-09T21:41:26+00:00 /usr/bin/pegasus-rc-client --prefix pegasus.catalog.replica.output --conf /home/vsaiadian/Hotsprings/workflow/work/vsaiadian/pegasus/noble-gas-reduction/run0002/pegasus.5484089135341852749.properties -v --insert /home/vsaiadian/Hotsprings/workflow/work/vsaiadian/pegasus/noble-gas-reduction/run0002/00/00/register_local_2_0.in"
error = /home/vsaiadian/Hotsprings/workflow/work/vsaiadian/pegasus/noble-gas-reduction/run0002//00/00/register_local_2_0.err
executable = /usr/share/pegasus/sh/pegasus-lite-local.sh
log = /home/vsaiadian/Hotsprings/workflow/work/vsaiadian/pegasus/noble-gas-reduction/run0002/noble-gas-reduction-0.log
notification = NEVER
output = /home/vsaiadian/Hotsprings/workflow/work/vsaiadian/pegasus/noble-gas-reduction/run0002//00/00/register_local_2_0.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 30)
priority = 60
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
wf_submit_dir = /home/vsaiadian/Hotsprings/workflow/work/vsaiadian/pegasus/noble-gas-reduction/run0002
pegasus_job_runtime = 0
pegasus_cores = 1
pegasus_gpus = 0
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "d3326321-b47e-49e9-8e88-50e0138644d1"
+pegasus_wf_uuid = "d3326321-b47e-49e9-8e88-50e0138644d1"
+pegasus_version = "5.1.3"
+pegasus_wf_name = "noble-gas-reduction-0"
+pegasus_wf_time = "20261009T214126+0000"
+pegasus_wf_xformation = "pegasus::rc-client"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "register_local_2_0"
+pegasus_job_class = 4
+pegasus_site = "local"
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
