######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : noble-gas-reduction, Index = 0, Count = null
# SUBMIT FILE NAME : blanks_tab_ID0000003.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 PATH=/usr/bin:/bin CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=5bef5c0a-1e95-422f-b779-e65dd0765b2c PEGASUS_WF_LABEL=noble-gas-reduction PEGASUS_DAG_JOB_ID=blanks_tab_ID0000003 PEGASUS_SITE=local GRIDSTART_CLEANUP='/bin/rm -rf blanks_tab_ID0000003.in.lof blanks_tab_ID0000003.out.lof ' _PEGASUS_WF_SUBMIT_DIR=/home/vsaiadian/Hotsprings/workflow/work/vsaiadian/pegasus/noble-gas-reduction/run0001 _PEGASUS_INITIAL_DIR=/home/vsaiadian/Hotsprings/workflow/work/scratch/vsaiadian/pegasus/noble-gas-reduction/run0001 _PEGASUS_TRANSFER_INPUT_FILES=blanks_tab,blank_ref.json,blanks.csv,gaslib.py,GAS_PROCESS.xlsx,$(wf_submit_dir)/pegasus-worker-5.1.3-x86_64_rhel_8.tar.gz,$(wf_submit_dir)/00/00/blanks_tab_ID0000003.in.lof,$(wf_submit_dir)/00/00/blanks_tab_ID0000003.out.lof,$(wf_submit_dir)/pegasus-lite-common.sh, _PEGASUS_TRANSFER_OUTPUT_FILES=blanks_tab.csv, PEGASUS_BIN_DIR=/usr/bin"
arguments = "/home/vsaiadian/Hotsprings/workflow/work/vsaiadian/pegasus/noble-gas-reduction/run0001/00/00/blanks_tab_ID0000003.sh "
error = /home/vsaiadian/Hotsprings/workflow/work/vsaiadian/pegasus/noble-gas-reduction/run0001//00/00/blanks_tab_ID0000003.err
executable = /usr/share/pegasus/sh/pegasus-lite-local.sh
initialdir = /home/vsaiadian/Hotsprings/workflow/work/scratch/vsaiadian/pegasus/noble-gas-reduction/run0001
log = /home/vsaiadian/Hotsprings/workflow/work/vsaiadian/pegasus/noble-gas-reduction/run0001/noble-gas-reduction-0.log
notification = NEVER
output = /home/vsaiadian/Hotsprings/workflow/work/vsaiadian/pegasus/noble-gas-reduction/run0001//00/00/blanks_tab_ID0000003.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 30)
priority = 40
request_cpus = $(pegasus_cores)
request_disk = $(pegasus_diskspace_mb) MB
request_memory = $(pegasus_memory_mb) MB
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
wf_submit_dir = /home/vsaiadian/Hotsprings/workflow/work/vsaiadian/pegasus/noble-gas-reduction/run0001
pegasus_job_runtime = 0
pegasus_cores = 1
pegasus_gpus = 0
pegasus_memory_mb = 2048
pegasus_diskspace_mb = 5120
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "5bef5c0a-1e95-422f-b779-e65dd0765b2c"
+pegasus_wf_uuid = "5bef5c0a-1e95-422f-b779-e65dd0765b2c"
+pegasus_version = "5.1.3"
+pegasus_wf_name = "noble-gas-reduction-0"
+pegasus_wf_time = "20261009T185313+0000"
+pegasus_wf_xformation = "blanks_tab"
+pegasus_wf_dax_job_id = "ID0000003"
+pegasus_wf_dag_job_id = "blanks_tab_ID0000003"
+pegasus_job_class = 1
+pegasus_site = "local"
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
