######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : noble-gas-reduction, Index = 0, Count = null
# SUBMIT FILE NAME : cleanup_noble-gas-reduction_0_local.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 PATH=/usr/bin:/bin CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=5bef5c0a-1e95-422f-b779-e65dd0765b2c PEGASUS_WF_LABEL=noble-gas-reduction PEGASUS_DAG_JOB_ID=cleanup_noble-gas-reduction_0_local PEGASUS_SITE=local _PEGASUS_WF_SUBMIT_DIR=/home/vsaiadian/Hotsprings/workflow/work/vsaiadian/pegasus/noble-gas-reduction/run0001 PEGASUS_BIN_DIR=/usr/bin _PEGASUS_CONNECT_STDIN=true"
arguments = "pegasus-kickstart  -n pegasus::cleanup -N null -i - -R local  -L noble-gas-reduction -T 2026-10-09T18:53:12+00:00 pegasus-transfer "
error = /home/vsaiadian/Hotsprings/workflow/work/vsaiadian/pegasus/noble-gas-reduction/run0001//00/00/cleanup_noble-gas-reduction_0_local.err
executable = /usr/share/pegasus/sh/pegasus-lite-local.sh
input = /home/vsaiadian/Hotsprings/workflow/work/vsaiadian/pegasus/noble-gas-reduction/run0001//00/00/cleanup_noble-gas-reduction_0_local.in
log = /home/vsaiadian/Hotsprings/workflow/work/vsaiadian/pegasus/noble-gas-reduction/run0001/noble-gas-reduction-0.log
notification = NEVER
output = /home/vsaiadian/Hotsprings/workflow/work/vsaiadian/pegasus/noble-gas-reduction/run0001//00/00/cleanup_noble-gas-reduction_0_local.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 30)
priority = 1000
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
wf_submit_dir = /home/vsaiadian/Hotsprings/workflow/work/vsaiadian/pegasus/noble-gas-reduction/run0001
pegasus_job_runtime = 0
pegasus_cores = 1
pegasus_gpus = 0
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "5bef5c0a-1e95-422f-b779-e65dd0765b2c"
+pegasus_wf_uuid = "5bef5c0a-1e95-422f-b779-e65dd0765b2c"
+pegasus_version = "5.1.3"
+pegasus_wf_name = "noble-gas-reduction-0"
+pegasus_wf_time = "20261009T185313+0000"
+pegasus_wf_xformation = "pegasus::cleanup"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "cleanup_noble-gas-reduction_0_local"
+pegasus_job_class = 8
+pegasus_site = "local"
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
