######################################################################
# PEGASUS WMS GENERATED SUBMIT FILE
# DAG : noble-gas-reduction, Index = 0, Count = null
# SUBMIT FILE NAME : create_dir_noble-gas-reduction_0_local.sub
######################################################################
stream_error  = false
stream_output = false
environment = "LANG=en_US.UTF-8 PATH=/usr/bin:/bin CONDOR_JOBID=$(cluster).$(process) PEGASUS_WF_UUID=3dcace93-b68e-4ce5-b9f9-3cc947189097 PEGASUS_WF_LABEL=noble-gas-reduction PEGASUS_DAG_JOB_ID=create_dir_noble-gas-reduction_0_local PEGASUS_SITE=local _PEGASUS_WF_SUBMIT_DIR=/home/vsaiadian/Hotsprings/workflow/work/vsaiadian/pegasus/noble-gas-reduction/run0004 PEGASUS_BIN_DIR=/usr/bin _PEGASUS_CONNECT_STDIN=true"
arguments = "pegasus-kickstart  -n pegasus::dirmanager -N null -i - -R local  -L noble-gas-reduction -T 2026-10-09T21:54:27+00:00 pegasus-transfer "
error = /home/vsaiadian/Hotsprings/workflow/work/vsaiadian/pegasus/noble-gas-reduction/run0004//00/00/create_dir_noble-gas-reduction_0_local.err
executable = /usr/share/pegasus/sh/pegasus-lite-local.sh
input = /home/vsaiadian/Hotsprings/workflow/work/vsaiadian/pegasus/noble-gas-reduction/run0004//00/00/create_dir_noble-gas-reduction_0_local.in
log = /home/vsaiadian/Hotsprings/workflow/work/vsaiadian/pegasus/noble-gas-reduction/run0004/noble-gas-reduction-0.log
notification = NEVER
output = /home/vsaiadian/Hotsprings/workflow/work/vsaiadian/pegasus/noble-gas-reduction/run0004//00/00/create_dir_noble-gas-reduction_0_local.out
periodic_release = False
periodic_remove = (JobStatus == 5) && ((CurrentTime - EnteredCurrentStatus) > 30)
priority = 800
submit_event_user_notes = pool:local
transfer_executable = false
universe = local
wf_submit_dir = /home/vsaiadian/Hotsprings/workflow/work/vsaiadian/pegasus/noble-gas-reduction/run0004
pegasus_job_runtime = 0
pegasus_cores = 1
pegasus_gpus = 0
+pegasus_generator = "Pegasus"
+pegasus_root_wf_uuid = "3dcace93-b68e-4ce5-b9f9-3cc947189097"
+pegasus_wf_uuid = "3dcace93-b68e-4ce5-b9f9-3cc947189097"
+pegasus_version = "5.1.3"
+pegasus_wf_name = "noble-gas-reduction-0"
+pegasus_wf_time = "20261009T215427+0000"
+pegasus_wf_xformation = "pegasus::dirmanager"
+pegasus_wf_dax_job_id = "null"
+pegasus_wf_dag_job_id = "create_dir_noble-gas-reduction_0_local"
+pegasus_job_class = 6
+pegasus_site = "local"
+pegasus_cluster_size = 1
queue
######################################################################
# END OF SUBMIT FILE
######################################################################
